# Generated by Django 4.1.4 on 2022-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=30)),
                ('customer_mobile_no', models.IntegerField(default=0)),
            ],
        ),
    ]
