# Generated by Django 4.1.4 on 2022-12-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customerdetail_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='subcategory',
        ),
    ]
