# Generated by Django 4.1.4 on 2022-12-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_customerdetail_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightbil',
            fields=[
                ('bil_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('meter_no', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
