# Generated by Django 4.1.4 on 2022-12-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_customerdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecblic',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerDetail',
        ),
    ]
