# Generated by Django 3.0.5 on 2023-01-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_address_order_city_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
