# Generated by Django 3.0.5 on 2023-01-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20230104_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Phone',
            new_name='phone',
        ),
    ]
